name: Star Notification
on:
    watch:
        types: [started]
    workflow_dispatch:

jobs:
    discord_notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send custom Discord message
              run: |
                  curl -H "Content-Type: application/json" \
                  -X POST \
                  -d '{
                    "username": "TruckNav Milestones",
                    "avatar_url": "https://raw.githubusercontent.com/Rares-Muntean/TruckNav-Sim/master/public/icon.png",
                    "embeds": [{
                      "title": "⭐ New Driver in the Fleet! ⭐",
                      "description": "[**${{ github.actor }}**](https://github.com/${{ github.actor }}) just starred the repo!\n\nThank you for supporting **TruckNav-Sim**.\nWe are now at **${{ github.event.repository.stargazers_count }}** stars. 🛣️",
                      "color": 3447003,
                      "thumbnail": { "url": "${{ github.event.sender.avatar_url }}" },
                      "footer": { "text": "TruckNav-Sim Community Hub" }
                    }]
                  }' \
                  ${{ secrets.DISCORD_WEBHOOK }}
